const Products = [
  {
    "id": 4,
    "categoryid": "3",
    "description": "adasdas",
    "name": "1000 Armed Dukar statue",
    "slug": "aasdas",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301120/zbzysngtxjwrdeamygja.jpg",
    "ribbon": "sdasd2",
    "onsale": true,
    "discount": "132.00",
    "discounttype": "",
    "shippinginfo": "asd123",
    "price": "999.00",
    "size": "25 x 25",
    "adddescription": "asdasdasd asd asd asd asd",
    "tags": "",
    "categoryslug": "featured",
    "sku": "114dasd",
    "stock": "101",
    "productid": "4"
  },
  {
    "id": 5,
    "categoryid": "4",
    "description": "We have traditionally hand-carved the statue of Amitabha Buddha in a pure oxidized copper body. We are the Kathmandu Valley artist whose artisan in making ancient Buddhist statues has passed through generations. We have depicted a deity seated atop a moon disc lotus seat with a peaceful expression. Finely hand-crafted Buddha and painted with acrylic colors portrayed with holding an alms bowl with both hands is mesmerizing. You can use this sculpture for different meditational or yoga activities. The vibrant halo illuminates his face, and the beautifully designed robe engulfs his presence. This statue will be a tremendous gift for a practitioner like you.",
    "name": "Statue of Amitabha Buddha",
    "slug": "b13",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1731171231/vps8eopeiql8seanrjww.jpg",
    "ribbon": "NBew",
    "onsale": true,
    "discount": "0.00",
    "discounttype": "",
    "shippinginfo": "",
    "price": "99.99",
    "size": "",
    "adddescription": "",
    "tags": "",
    "categoryslug": "statues",
    "sku": "SKU11234",
    "stock": "900",
    "productid": "5"
  },
  {
    "id": 7,
    "categoryid": "0",
    "description": "In publishing and graphic design, Lorem ipsum (/?l??.r?m ??p.s?m/) is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available. It is also used to temporarily replace text in a process called greeking, which allows designers to consider the form of a webpage or publication, without the meaning of the text influencing the design.\n\nLorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum (\"pain itself\").",
    "name": "De finibus bonorum et malorum, a 1st-century BC",
    "slug": "dasd",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301162/ozik7qjkfcvz3pc70ifs.jpg",
    "ribbon": "EXPENSIVE",
    "onsale": false,
    "discount": "0.00",
    "discounttype": "",
    "shippinginfo": "",
    "price": "100000.00",
    "size": "",
    "adddescription": "",
    "tags": "",
    "categoryslug": "",
    "sku": "SKU7897",
    "stock": "5465",
    "productid": "7"
  },
  {
    "id": 8,
    "categoryid": "0",
    "description": "This 1000-armed Ushnisha Sitatapatra statue is a hand-crafted masterpiece of Nepalese craftsmanship sculpted in our studio. It is made from brass and copper alloy and intricately designed to radiate celestial energy. The deity is symbolic of compassion, wisdom and protection from obstacles, making it a powerful spiritual object. Its 1000 arms evoke divinity while its meticulous design imbues your home with elegance and beauty. Sitatapatra appears in a variety of forms, including a thousand faces, arms, and legs, or simply as a beautiful feminine deity. She is best known for her \"white umbrella,\" which she is holding up with her left arm as a status symbol. She is often credited with inventing the \"golden wheel.\" The tremendous halo behind the statue depicts a thousand arms with intricate designs and a halo of fire that was meticulously created. This Dukar statue took our artists months to complete, and the mesmerizing and precise detail provided by our artists is flawless.\n\nThis 1000 Armed Dukar statue would make an excellent gift for a practitioner like you.",
    "name": "Ushnisha Sitatapatra statue",
    "slug": "edf",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301223/mnltg7bsagkbuixfzc02.jpg",
    "ribbon": "",
    "onsale": true,
    "discount": "0.00",
    "discounttype": "",
    "shippinginfo": "",
    "price": "47299.99",
    "size": "",
    "adddescription": "",
    "tags": "",
    "categoryslug": "",
    "sku": "SKU112344",
    "stock": "899",
    "productid": "8"
  },
  {
    "id": 13,
    "categoryid": "3",
    "description": "A beautifully handcrafted Buddha statue made from brass, perfect for home decor and spiritual spaces.",
    "name": "Traditional Buddha Statue",
    "slug": "tradition",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301295/cufdaw0fdod40iefowvz.jpg",
    "ribbon": "Bestseller",
    "onsale": false,
    "discount": "10.00",
    "discounttype": "Percentage",
    "shippinginfo": "Free shipping within Nepal",
    "price": "120.00",
    "size": "12 inches",
    "adddescription": "This statue is intricately designed by skilled artisans, reflecting the rich cultural heritage of Nepal.",
    "tags": "",
    "categoryslug": "featured",
    "sku": "SKU112348",
    "stock": "10",
    "productid": "13"
  },
  {
    "id": 14,
    "categoryid": "4",
    "description": "A stunning hand-painted Thanka depicting traditional Buddhist art, ideal for wall decor.",
    "name": "Hand-Painted Thanka",
    "slug": "hand",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301320/kumsq1dnfmjbwntxobxm.jpg",
    "ribbon": "New Arrival",
    "onsale": false,
    "discount": "0.00",
    "discounttype": "None",
    "shippinginfo": "Free shipping on orders over $150",
    "price": "200.00",
    "size": "24x36 inches",
    "adddescription": "This Thanka is painted using natural dyes and pigments, showcasing the meticulous craftsmanship of Nepali artists.",
    "tags": "",
    "categoryslug": "statues",
    "sku": "",
    "stock": "0",
    "productid": "14"
  },
  {
    "id": 15,
    "categoryid": "5",
    "description": "A vibrant Dhaka fabric scarf, handwoven with traditional patterns, perfect for any occasion.",
    "name": "Dhaka Fabric Scarf",
    "slug": "dhaka",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301507/uoyorz5oxtc7ly4v7e54.jpg",
    "ribbon": "Limited Edition",
    "onsale": false,
    "discount": "15.00",
    "discounttype": "Percentage",
    "shippinginfo": "Standard shipping rates apply",
    "price": "50.00",
    "size": "70x20 inches",
    "adddescription": "This scarf is made from high-quality Dhaka fabric, known for its unique and colorful designs, representing the traditional weaving techniques of Nepal.",
    "tags": "",
    "categoryslug": "thankas",
    "sku": "",
    "stock": "0",
    "productid": "15"
  },
  {
    "id": 16,
    "categoryid": "3",
    "description": "An intricately carved wooden mask, perfect for adding a touch of Nepali culture to your home decor.",
    "name": "Wooden Carved Mask",
    "slug": "wooden",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301452/myvppf0x5lyaxlcyfjdx.jpg",
    "ribbon": "Handcrafted",
    "onsale": false,
    "discount": "0.00",
    "discounttype": "None",
    "shippinginfo": "Free shipping within Nepal",
    "price": "80.00",
    "size": "15 inches",
    "adddescription": "This mask is handcrafted by skilled artisans using traditional techniques, making each piece unique.",
    "tags": "",
    "categoryslug": "featured",
    "sku": "",
    "stock": "0",
    "productid": "16"
  },
  {
    "id": 17,
    "categoryid": "22",
    "description": "A beautiful silver beaded necklace, perfect for adding a touch of elegance to any outfit.",
    "name": "Silver Beaded Necklace",
    "slug": "silver",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301543/aubjhdaqa5pw0npfff0v.jpg",
    "ribbon": "Bestseller",
    "onsale": false,
    "discount": "20.00",
    "discounttype": "Percentage",
    "shippinginfo": "Standard shipping rates apply",
    "price": "70.00",
    "size": "18 inches",
    "adddescription": "This necklace is made from high-quality silver beads, reflecting the traditional jewelry-making techniques of Nepal.",
    "tags": "",
    "categoryslug": "jewellery",
    "sku": "",
    "stock": "0",
    "productid": "17"
  },
  {
    "id": 18,
    "categoryid": "5",
    "description": "A stylish Dhaka fabric bag, perfect for everyday use or as a unique gift.",
    "name": "Traditional Dhaka Bag",
    "slug": "traditio",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301597/q6sttt99fwf1fcconn2y.jpg",
    "ribbon": "New Arrival",
    "onsale": false,
    "discount": "0.00",
    "discounttype": "None",
    "shippinginfo": "Standard shipping rates apply",
    "price": "40.00",
    "size": "12x10 inches",
    "adddescription": "This bag is made from traditional Dhaka fabric, known for its vibrant colors and unique patterns.",
    "tags": "",
    "categoryslug": "thankas",
    "sku": "",
    "stock": "0",
    "productid": "18"
  },
  {
    "id": 19,
    "categoryid": "3",
    "description": "A complete set of singing bowls, perfect for meditation and relaxation.",
    "name": "Singing Bowl Set",
    "slug": "singing",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301641/ejzhkr8fopptgosscrno.jpg",
    "ribbon": "Bestseller",
    "onsale": false,
    "discount": "10.00",
    "discounttype": "Percentage",
    "shippinginfo": "Free shipping within Nepal",
    "price": "150.00",
    "size": "Various sizes",
    "adddescription": "This set includes multiple singing bowls, each handcrafted by skilled artisans to produce soothing sounds for meditation.",
    "tags": "",
    "categoryslug": "featured",
    "sku": "",
    "stock": "0",
    "productid": "19"
  },
  {
    "id": 20,
    "categoryid": "4",
    "description": "A traditional Thanka painting, perfect for adding a touch of Nepali art to your home.",
    "name": "Traditional Thanka Painting",
    "slug": "painting",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301685/ifuwzack7th3yfpuydx9.jpg",
    "ribbon": "Handcrafted",
    "onsale": false,
    "discount": "0.00",
    "discounttype": "None",
    "shippinginfo": "Free shipping on orders over $150",
    "price": "180.00",
    "size": "20x30 inches",
    "adddescription": "This Thanka painting is created using traditional techniques and natural pigments, making each piece unique.",
    "tags": "",
    "categoryslug": "statues",
    "sku": "",
    "stock": "0",
    "productid": "20"
  },
  {
    "id": 21,
    "categoryid": "3",
    "description": "A beautifully crafted incense holder, perfect for creating a calming atmosphere in your home.",
    "name": "Handmade Incense Holder",
    "slug": "handmade",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301723/gblorm3kfvjciddrnwks.jpg",
    "ribbon": "New Arrival",
    "onsale": false,
    "discount": "5.00",
    "discounttype": "Percentage",
    "shippinginfo": "Standard shipping rates apply",
    "price": "25.00",
    "size": "8 inches",
    "adddescription": "This incense holder is handcrafted by skilled artisans, reflecting the traditional craftsmanship of Nepal.",
    "tags": "",
    "categoryslug": "featured",
    "sku": "",
    "stock": "0",
    "productid": "21"
  },
  {
    "id": 22,
    "categoryid": "5",
    "description": "A warm and stylish Dhaka shawl, perfect for any occasion.",
    "name": "Traditional Dhaka Shawl",
    "slug": "dhak",
    "banner": "http://res.cloudinary.com/craftsnepal/image/upload/v1732301787/j6fnvxcvaa3xam6nibws.jpg",
    "ribbon": "Limited Edition",
    "onsale": false,
    "discount": "10.00",
    "discounttype": "Percentage",
    "shippinginfo": "Standard shipping rates apply",
    "price": "60.00",
    "size": "80x30 inches",
    "adddescription": "This shawl is made from high-quality Dhaka fabric, known for its unique and colorful designs, representing the traditional weaving techniques of Nepal.",
    "tags": "",
    "categoryslug": "thankas",
    "sku": "",
    "stock": "0",
    "productid": "22"
  }
];

export default Products;